### ISSUE TITLE
Code of clock shown in the gif

### ISSUE THREAD

**Issue by matantech** [GamgeeNL/react-native-clock-interval#2]
Hi, 
Is it possible to get the full code of the example shown in the gif?
I'm trying to make the indicators images as the gif showa and it looks like it's almos impossible.
Thanks

**Comment by Iskander508** [comment]
Added example project with clock implementation in master branch

**Comment by matantech** [comment]
Thanks!
I couldn’t find the specific code where you
make the line edges rounded. Can you please provide it?
Thank you in advance 
Matan

**Comment by Iskander508** [comment]
> I couldn’t find the specific code where you
> make the line edges rounded. Can you please provide it?
You mean the drag indicators with bed and bell icons? It's just a View with borderRadius style
